#### Consider the below code to answer further questions:
        
#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)
#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a codeto print the data types of both the variables.

Ans:

In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']

In [3]:
array_list = np.array(list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

In [10]:
array_list.dtype

dtype('<U1')

list and array_list both contain data is string. but list has not option or function. to show data of each variable. so it shows type list.

but numpy as has option to show data type of each variable by array.dtype.

Yes , there any difference in the data type of variables list_ and array_list.

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

Ans:

In [23]:
for i in list_:
    print(i , type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [28]:
for j in array_list:
    print(j , i.dtype)

1 <U1
2 <U1
3 <U1
4 <U1
5 <U1


### or

In [27]:
array_list.dtype

dtype('<U1')

#### Q3. Considering the following changes in the variable, array_list:
#### array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list?
#### If so then print the data types of each and every element present in both the variables, list_and array_list.

Ans:

In [32]:
list_

['1', '2', '3', '4', '5']

In [33]:
type(list_)

list

In [29]:
array_list = np.array(object = list_, dtype = int)

In [30]:
array_list

array([1, 2, 3, 4, 5])

In [31]:
array_list.dtype

dtype('int32')

In [34]:
for i in list_:
    
    print(i , type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


Yes , there is difference in the data type of the elements present in both the variables, list_ and array_list.

list_ has string data and array_list has data of integer.(int32 byte).

#### Consider the below code to answer further questions:
#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)
#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

Ans:

In [39]:
num_list = [[1,2,3],[4,5,6]]

In [40]:
num_array = np.array(num_list)

In [41]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

#### shape : shape is used for to check count of rows and columns

In [43]:
num_array.shape

(2, 3)

#### size : size is used for to show count of numbers present in array.

In [44]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

Ans:

In [51]:
arr = np.array([[0,0,0],[0,0,0],[0,0,0]] , dtype = 'float')

In [52]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Ans:

#### This is the array

In [55]:
arr = np.eye(5,5 , dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [63]:
type(arr)

numpy.ndarray

In [60]:
np.identity(5 , dtype = 'float')

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
type(np.identity(5 , dtype = 'float'))

numpy.ndarray

#### This is the matrix

In [56]:
import numpy.matlib as nm

In [57]:
nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [62]:
type(nm.eye(5,5))

numpy.matrix